name: Postprocess on ch update

on:
  workflow_dispatch:
  push:
    paths:
      - 'data/ch'
    

jobs:
  post-process-on-ch-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Checkout ch data
        uses: actions/checkout@v3
        with:
          repository: gf-data-tools/gf-data-ch
          path: data/ch
          token: ${{ secrets.PERSONAL_TOKEN }}   
      - name: Checkout Uncensorship
        uses: actions/checkout@v3
        with:
          repository: gf-data-tools/anti-harmonization
          path: anti-harmonization
          token: ${{ secrets.PERSONAL_TOKEN }}
          
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD HH:mm:ss
          utcOffset: "+08:00"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
          
      - name: Analyze
        run: |
          echo "::group::Enemy Team Analyze"
          python enemy_team_analyze/enemy_team_analyze.py
          python enemy_stats_analyze/main.py
          echo "::endgroup::"

          echo "::group::Anti Harmonization"
          python anti-harmonization/main.py
          cp anti-harmonization/catchdata.dat outputs/catchdata.dat
          echo "::endgroup::"
      
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "DataAnalyze autoupdate at ${{ steps.current-time.outputs.formattedTime }}"
          file_pattern: outputs/catchdata.dat enemy_team_analyze/* enemy_stats_analyze/*
