name: gfl-data-miner auto update bot

on:
  workflow_dispatch:
    inputs:
      cmdargs:
        description: 'Commandline Arguments'     
        required: false
        default: 'tw kr jp us ch' 
        type: string
  schedule:
    - cron: '30 1,2-14/3 * * *'
    - cron: '0 4-13/3 * * 4'
  push:
    paths:
      - 'data-miner'
    

jobs:
  gfl-data-miner-update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: 'recursive'

      - run: |
          git submodule foreach --recursive git checkout main
          git config --global core.autocrlf input
          git config --global core.safecrlf false

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - run: "pip install -r data-miner/requirements.txt"

      - name: Data Miner
        id: data-miner
        continue-on-error: true
        run: | 
          python data-miner/data_miner.py ${{ inputs.cmdargs || 'tw kr jp us ch at' }} ${{ github.event_name=='push' && '-f' || '' }}
      
      - name: Commit-tw
        continue-on-error: true
        uses: ./.github/actions/DataMinerCommit
        if: ${{ env.commit-message-tw }}
        with:
          commit_message: ${{ env.commit-message-tw }}
          repository: data/tw
          bot_token: ${{ secrets.DINGTALK_TOKEN }}
      - name: Commit-kr
        continue-on-error: true
        uses: ./.github/actions/DataMinerCommit
        if: ${{ env.commit-message-kr }}
        with:
          commit_message: ${{ env.commit-message-kr }}
          repository: data/kr
          bot_token: ${{ secrets.DINGTALK_TOKEN }}
      - name: Commit-jp
        continue-on-error: true
        uses: ./.github/actions/DataMinerCommit
        if: ${{ env.commit-message-jp }}
        with:
          commit_message: ${{ env.commit-message-jp }}
          repository: data/jp
          bot_token: ${{ secrets.DINGTALK_TOKEN }}
      - name: Commit-us
        continue-on-error: true
        uses: ./.github/actions/DataMinerCommit
        if: ${{ env.commit-message-us }}
        with:
          commit_message: ${{ env.commit-message-us }}
          repository: data/us
          bot_token: ${{ secrets.DINGTALK_TOKEN }}
      - name: Commit-ch
        continue-on-error: true
        uses: ./.github/actions/DataMinerCommit
        if: ${{ env.commit-message-ch }}
        with:
          commit_message: ${{ env.commit-message-ch }}
          repository: data/ch
          bot_token: ${{ secrets.DINGTALK_TOKEN }}
      - name: Commit-at
        continue-on-error: true
        uses: ./.github/actions/DataMinerCommit
        if: ${{ env.commit-message-at }}
        with:
          commit_message: ${{ env.commit-message-at }}
          repository: data/at
          bot_token: ${{ secrets.DINGTALK_TOKEN }}
      - name: Push
        run: git push
