name: Rescue Event Auto Update

on:
  push:
    paths:
      - 'rescue_event_history/doll_obtain_info.tsv'
      - 'gh-pages'
  workflow_dispatch:

jobs:
  RescueEventUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          submodules: 'recursive'
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+08:00"
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Rescue Event History Update
        uses: ./.github/actions/RescueEvent
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./gh-pages