name: Rescue Event Auto Update

on:
  push:
    paths:
      - 'rescue_event_history/doll_obtain_info.tsv'
      - 'rescue_event_history/*.py'
  workflow_dispatch:

jobs:
  RescueEventUpdate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Checkout ch data
        uses: actions/checkout@v2
        with:
          repository: gf-data-tools/gf-data-ch
          path: data/ch
          token: ${{ secrets.PERSONAL_TOKEN }}
      - uses: ./.github/actions/BotConfig
      - name: Get current time
        uses: josStorer/get-current-time@v2
        id: current-time
        with:
          format: YYYY-MM-DD
          utcOffset: "+08:00"
      - name: Setup Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: '3.8'
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: GenerateTable
        shell: bash
        run: |
          python rescue_event_history/rescue_log_table.py 
          python rescue_event_history/generate_gantt.py 
      - name: Prepare gh-pages
        shell: bash
        run: |
          mkdir -p gh-pages/rescue_event_history
          cp rescue_event_history/*.html gh-pages/rescue_event_history/
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "RescueEvent autoupdate at ${{ steps.current-time.outputs.formattedTime }}"
          file_pattern: rescue_event_history/*.html gh-pages/rescue_event_history/*.html