name: 'Submodule Sync'

on:
  # Allows you to run this workflow manually from the Actions tab or through HTTP API
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  repository_dispatch:
    types: [submodule_sync]
    
concurrency: repo_update

jobs:
  sync:
    name: 'Submodules Sync'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.PERSONAL_TOKEN }}
        submodules: "recursive"

    # Update references
    - name: Git Sumbodule Update
      run: |
        git submodule foreach --recursive git checkout main

    - name: Commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Auto updated submodule references"
